config/routes.rb
Rails.application.routes.draw do
  
resources "entries"
  

  root 'welcome#witam'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end
  
  def show
    @entry = Entry.find(params["id"])
  end
  
  
  def new
  end
  
  def create
    entry_params = params["entry"].permit("title", "contents")
  entry = Entry.create(entry_params)
  redirect_to(entry_path(entry))
  end
  
  def edit
    @entry = Entry.find(params["id"])
  end
  
  def update
    entry_params = params["entry"].permit("title", "contents", "picture_url")
  entry = Entry.find(params["id"])
  entry.update(entry_params)
  redirect_to(entries_path)
  end
  
  def destroy
    Entry.find(params["id"]).delete
    redirect_to(entries_path)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def witam
      @websites = [
    ["http://railsgirls.com", "Rails Girls"],
    ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
    ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
  ]
    
    @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/destroy.html.erb
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
<p><%= form.label("picture_url") %></p>
<p><%= form.text_field("picture_url") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to("Back to main", root_path) %></p>

app/views/entries/index.html.erb
<p><%= link_to("Back to main", root_path) %></p> 
<p><%= link_to("New entry", new_entry_path) %></p>

<% for entry in @entries %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
<img src="<%= entry.picture_url %>" >
<% end %>
 

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
<p><%= form.label("picture_url") %></p>
<p><%= form.text_field("picture_url") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to("Back to main", root_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  
<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
<p><%= link_to("Delete entry", entry_path(@entry), method: 'DELETE') %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to("Back to main", root_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.css"  rel="stylesheet">
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/witam.html.erb
<div class="col-xs-12 text-center"
<% a = Time.now %>
<%= a %>
<h1> <div class="duze">MY RAILS GIRLS DIARY</div></h1>
  
  
  <img src="http://2.bp.blogspot.com/-pZnJbP7GAiU/VIxyEyNErEI/AAAAAAAAC9E/jI_8Oo1t8n0/s1600/wzorek.png" height="40"/>
  <h1><p class="male"><%= link_to("MY ENTRIES", entries_path) %></p></h1>
  <br>
  <br>
  <div>
    <img src="http://2.bp.blogspot.com/-pZnJbP7GAiU/VIxyEyNErEI/AAAAAAAAC9E/jI_8Oo1t8n0/s1600/wzorek.png" height="40"/>
    <h1><p class="male">SOME STUFF</p></h1>
    
    <ul>
<% for url, name in @websites %>
  <li><a href="<%= url %>"><%= name %></a></li>
<% end %>
     
    </ul>
  </div>

  <br>
  <br>
  <img src="https://humancoders-formations.s3.amazonaws.com/uploads/course/logo/15/formation-ruby.png" height="200"/>
</div>